### ISSUE TITLE
Create a new card with an uploaded custom file using the Api

### ISSUE THREAD

**Issue by alianza** [Print-one/print-one-js#30]
**Describe the bug**
We'd like our customers to be able to upload their own images to order a card using that image.
How is it possible to create a new template and create an new order using a custom file uploaded using the Api. 

**To Reproduce**
Currently we do the following:

1. We perform the `uploadCustomFile()` method to upload a custom file.
2. We'd like to use this custom file to create a new template or insert the image as variable in an existing template.
3. Finally we want to create the order using `createOrder()` (Which we already do currently, but using the uploaded custom file as image)

**Expected behavior**
It's unclear to us what the correct steps are to achieve this functionality exactly.

We don't receive an image url when uploading a custom file to use in the template, we don't see another way to include the custom file as image in a template.

If there are other steps required or preferred to achieve this type of functionality please let us know as we are unsure this sequence of steps is correct :)

**Comment by PaulRill00** [comment]
Hi @alianza,

To achieve what you are describing here you can do the following:

1. Upload the file and retrieve the `fileName` from the upload response.
2. Create or use the template
  2.1. When creating a new template for each customfile you can use the following: `<img src="{{{ file 'the-retrieved-filename.png' }}}" />`
  2.2. When you want to re-use the same template, make sure the following is in the template HTML: `<img src="{{{ file filename }}}" />` and then make sure to add the merge-variable `filename: retrieved-file-name` when creating the order
3. Create the order, incase of you using 2.1. you don't need to add the filename as a merge-variable

I hope this helps

**Comment by alianza** [comment]
Hey @PaulRill00,

Thank you for the swift response, this helped a lot! We have decided to go with option 2.2 and reuse a template and add the `filename` merge variable to it when creating the order. This seems to work fine. 

One more thing, is there a way to generate a preview image for the reusable template that includes the custom uploaded file? I'm able to generate a pdf from the order but I'd like to show a preview before creating the actual order itself.

Thanks again!

**Comment by PaulRill00** [comment]
Hi @alianza,

Good to hear it's worked so far.
Yes - if you use the [Create Preview Endpoint](https://api.print.one/docs/v2#operation/Template/createTemplatePreview) you should be able to include the 'filename' merge-variable to get a preview of the actual file used.
