### ISSUE TITLE
getOrders() call returns both live and test data with test api key

### ISSUE THREAD

**Issue by robinveraconnect** [Print-one/print-one-js#5]
I started implementing the PrintOne client and while testing saw that also live orders are being fetched using our test key.

Probably straight forward but here is my code:
`const printOne = new PrintOne(PRINT_ONE_API_KEY);
const test = await printOne.getOrders();`

Let me know if you need more information.

**Comment by UnderKoen** [comment]
Hey,

TEST and LIVE keys are almost identical in usage, the difference can be read [here](https://help.print.one/api/authentication-and-api-keys).

If you want to filter live vs test orders, you can use the [`isBillable`](https://github.com/Print-one/print-one-js/wiki/PrintOne#:~:text=options.filter.isBillable) filter. This filter allows you to specify whether the orders should be billable (live) or non-billable (test).

Here’s an updated snippet for your code:
```typescript
const printOne = new PrintOne(PRINT_ONE_API_KEY);
const test = await printOne.getOrders({
    filter: {
        isBillable: false, // Set to true for live orders, false for test orders
    }
});
```
